---
title: "Integrating"
author: "Johan Ravn Cornelius"
date: "2025-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The double-well model:
```{r}
sigma <- 1
y <- 0.01
epsilon <- 0.1
```


```{r}
bias_on_h3_scale <- function(b,x0){
  N <- function(x){(1/epsilon)*(-x^3-y+3*b^2*x+b-3*b^3)}
  dN <- function(x){(1/epsilon)*(-3*x^2+3*b^2)}
  d2N <- function(x){-6*x/epsilon}
  d3N <- function(x){-6/epsilon}
  A <- (1-3*b^2)/epsilon
  E <- function(x){ 
    (3/8)*A*dN(x)*N(x) + (1/4)*A^2*N(x) + (1/6)*A^3*(x-b) + (1/6)*d2N(x)*N(x)^2+(1/6)*dN(x)^2*N(x) +  (1/4)*dN(x)*A^2*(x-b) + (1/4)*d2N(x)*A^2*(x-b)^2 + (3/8)*d2N(x)*N(x)*A*(x-b) + (1/8)*dN(x)^2*A*(x-b)+ sigma^2 *( (1/4)*A*d2N(x) + (3/16)*d2N(x)*dN(x)+(1/4)*d3N(x)*A*(x-b)+(3/16)*d3N(x)*N(x) )   }
  true_E <- function(x){
    (1/3)*A*dN(x)*N(x) + (1/6)*A^2*N(x) + (1/6)*A^3*(x-b) + (1/6)*d2N(x)*N(x)^2+(1/6)*dN(x)^2*N(x) +  (1/3)*dN(x)*A^2*(x-b) + (1/6)*d2N(x)*A^2*(x-b)^2 + (1/3)*d2N(x)*N(x)*A*(x-b) + (1/6)*dN(x)^2*A*(x-b)+ sigma^2 *( (1/4)*A*d2N(x) + (1/4)*d2N(x)*dN(x)+(1/12)*d3N(x)*A*(x-b)+(1/12)*d3N(x)*N(x) ) }
  err <- function(x){ (E(x)-true_E(x))}
  return(abs(err(x0)))
}
abs_bias_on_h3_scale <- function(b,x0){
  abs(bias_on_h3_scale(b,x0))
}
```

Invariant distribution:
```{r}
inv <- function(x){(2/sigma^2) * exp(2*(0.5*x^2-0.25*x^4-y*x)/(epsilon*sigma^2))}
Z <- integrate(inv,-Inf,Inf)$value
mu <- function(x){ inv(x)/Z}
```

Separatrix:
```{r}
library(RConics)
```

```{r}
uns <- median(cubic(c(-1,0,1,-y))) #unstable fixed point
P1 <- integrate(mu,uns,Inf)$value
P2 <- integrate(mu,-Inf,uns)$value
```

Average theoretical bias:
```{r}
B1 <- function(b){
  integrand <- function(x){bias_on_h3_scale(b,x)*mu(x)}
  integrate( integrand,uns,Inf )$value/P1
} #B1(b) = E[B_b(X) | X >uns]
B2<- function(b){
  integrand <- function(x){bias_on_h3_scale(b,x)*mu(x)}
  integrate( integrand,-Inf,uns )$value/P2
}
```

Split in the following way:
When x>uns, linearize around b1=argmin_b |B_1(b)|.

Plot:
```{r}
bs <- seq(-1,1,length.out=300)
biases1 <- rep(NA,length(bs))
biases2<- rep(NA,length(bs))
for(i in 1:length(bs)){
  biases1[i] <- B1(bs[i])
  biases2[i] <- B2(bs[i])
}
plot(bs,biases1)
abline(0,0)
plot(bs,biases2)
abline(0,0)
```

