---
title: "density markdown without  mean bias"
output: html_document
date: "2026-07-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "facet distributions"
author: "Johan Ravn Cornelius"
date: "2026-05-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source('Brownian_motion.R',keep.source = TRUE)
source('EM.R',keep.source = TRUE)
library(ggplot2)
library(latex2exp)
library(cowplot)
library(tidyverse)
library(extrafont)
```

##Figure 1

Sample paths:
```{r}
eps1 <- 0.1
eps2 <- 0.25
y1 <- -0.05
y2 <- 0
sigma1 <- 1.7
sigma2 <- 1.2
F1 <- function(x){(x-x^3-y1)/eps1}
F2 <- function(x){(x-x^3-y2)/eps2}
G1 <- function(x){sigma1}
G2 <- function(x){sigma2}

x0 <- c(0)
n_paths <- 1
h <- 0.0001
T <- 30
m <- T/h +1
times <- seq(0,T,by=h)

W_increments <- rnorm(m,0,sqrt(h))
W_increments[1]<-0

EM <-  function(F,G){
  X_e <- rep(x0,m)
  for(i in (2:m)){
    X_e[i] <- X_e[i-1] + F(X_e[i-1])*h + G(X_e[i-1])*W_increments[i] } 
  return(X_e)
}
path1 <- EM(F1,G1)
path2 <- EM(F2,G2)

data1<- data.frame(matrix(nrow=length(path1),ncol=2))
names(data1) <- c("X", "t")
data1$X <- path1
data1$t <- times
data1$param <- as.character(1)

data2<- data.frame(matrix(nrow=length(path1),ncol=2))
names(data2) <- c("X", "t")
data2$X <- path2
data2$t <- times
data2$param <- as.character(2)

data <- rbind(data1, data2)

my_labeller <- as_labeller(c(`1`="theta[1]", `2`="theta[2]"),  default = label_parsed)

samplepath_p <- ggplot(data,aes(x=t,y=X))+
  geom_line(lwd=0.15)+
  facet_wrap(~param,ncol=1, labeller = my_labeller)+
  scale_y_continuous(minor_breaks = seq(-2, 1.5, 0.5))+
  labs(x="t", y=TeX('$X_t$'))+
  theme_bw(base_size=20)+
  theme(panel.grid.major = element_blank(), 
       panel.grid.minor = element_blank())+
  theme(legend.position="right",legend.key.size= unit(1.2, "cm"),)+
  theme(strip.text.x = element_text(size = 16, color = "black", face = "bold"),
        strip.text.y = element_text(size = 16, color = "black", face = "bold"),
        strip.text = element_text(face="bold"),
        strip.background = element_rect(fill="grey")  ) 
samplepath_p
```

Drift functions:
```{r}
xs <- seq(-1.5,1.5,by=0.001)
U1 <- function(x){(0.25*x^4 - 0.5* x^2 + x*y1)/eps1}
U2 <- function(x){(0.25*x^4 - 0.5* x^2 + x*y2)/eps2}
U1s <- U1(xs)
U2s <- U2(xs)
data1 <- data.frame(cbind(xs,U1s))
names(data1) <- c("x","Ux")
data1$theta <- as.character(1)
data2 <- data.frame(cbind(xs,U2s))
names(data2) <- c("x","Ux")
data2$theta <- as.character(2)
data <- rbind(data1,data2)
my_labeller <- as_labeller(c(`1`="theta[1]", `2`="theta[2]"),
                           default = label_parsed)
potential_p <-  ggplot(data=data,aes(x=x,y=Ux))+
  geom_line(lwd=0.9)+
  facet_wrap(~theta,ncol=1,
             scales="free_y",
             labeller=my_labeller
             )+
  geom_vline(xintercept=-1/sqrt(3),linetype=2)+
  geom_vline(xintercept=1/sqrt(3),linetype=2)+
  theme_bw(base_size=20  )+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(legend.position="right",legend.key.size= unit(1.2, "cm"),)+
  theme(strip.text.x = element_text(size = 16, color = "black", face = "bold"),
        strip.text.y = element_text(size = 16, color = "black", face = "bold"),
        strip.text = element_text(face="bold"),
        strip.background = element_rect(fill="grey"))+
  labs(x="x",y="U(x)")
potential_p
```



##Figure 2

```{r}

#Number of simulations:
M <- 2000
#Parameters:
y <- -0.05
eps <- 0.1
sigma <- 1.7
#Choice of transition density:
x0 <- -1.3
x0_left <- x0
h <- 0.08



#Splitting scheme functions:
F <- function(x){(x-x^3-y)/eps}
G <- function(x){sigma}
DF <- function(x){(1-3*x^2)/eps}
A <- function(c){DF(c)}
btilde <- function(c){ c - F(c)/DF(c) }
N <- function(x,c){(-x^3+3*c^2*x-2*c^3)/eps}
muh <- function(x,h,c){exp(A(c)*h)*x+(1-exp(A(c)*h))*btilde(c)}
Omegah <- function(h,c){  sigma^2 * (exp(2*A(c)*h)-1)/(2*A(c))  }
fh_fun <- function(x, h,c) {
  ODEfun <- function(t, state, parms) {
    u1 <- state[1]
    du1 <- N(u1,c)
    list(c(du1)) }
  out <- deSolve::ode(y = x, times = c(0, h), func = ODEfun, parms = NULL, method = 'lsoda')
  as.numeric(out[nrow(out), -1])
}

#Simulating EM steps:
hEM <- h/2000
EMtimes <- seq(0,h,by=hEM)
EMsim <- rep(NA,M)
for(i in 1:M){
  EMsteps <-  EM_sim_fast(F,G,x0,EMtimes,n_paths=1,progress = FALSE)[[1]]
  EMsim[i] <- EMsteps[nrow(EMsteps),1]
}
EMdata <- data.frame(EMsim)
EMdata$scheme <- "True distribution (EM)"
EMdata$x0 <- x0
names(EMdata) <- c("sim", "scheme", "Initial value")

#Function for simulating one-step predictions:
StrangSim <- function(x0,h,c,M){
  X0 <- rep(x0,M)
  xi <- rnorm(M,0,sqrt(Omegah(h,c)))
  step1 <- mapply(fh_fun,X0,h/2,c)
  step2 <- mapply(muh,step1,h,c)+xi
  step3 <- mapply(fh_fun,step2,h/2,c)
  return(step3)
}

#Splitting around negative stable fixed point:
StrangDataFix <- data.frame(StrangSim(x0,h, min(Re(polyroot(c(-y,1,0,-1))))  ,M))
StrangDataFix$scheme <- "Fixed point"
StrangDataFix$x0 <- x0
names(StrangDataFix) <- c("sim","scheme", "Initial value")

#Splitting around opposite stable fixed point:
StrangDataOpp <- data.frame(StrangSim(x0,h, max(Re(polyroot(c(-y,1,0,-1))))  ,M))
StrangDataOpp$scheme <- "Opposite fixed point"
StrangDataOpp$x0 <- x0
names(StrangDataOpp) <- c("sim","scheme","Initial value")

#Local splitting around x0:
StrangDataEachPoint <- data.frame(StrangSim(x0,h, x0  ,M))
StrangDataEachPoint$scheme <- "Local Strang"
StrangDataEachPoint$x0 <- x0
names(StrangDataEachPoint) <- c("sim","scheme","Initial value")

#Combine data for x0 in A1
data <- rbind(EMdata, StrangDataFix, StrangDataOpp, StrangDataEachPoint)

#Repeat for x0 in A3
x0 <- 0.6
EMsim2 <- rep(NA,M)
for(i in 1:M){
  EMsteps2 <-  EM_sim_fast(F,G,x0,EMtimes,n_paths=1,progress = FALSE)[[1]]
  EMsim2[i] <- EMsteps2[nrow(EMsteps2),1]
}
EMdata2 <- data.frame(EMsim2)
EMdata2$scheme <- "True distribution (EM)"
EMdata2$x0 <- x0
names(EMdata2) <- c("sim", "scheme", "Initial value")
StrangDataFix2 <- data.frame(StrangSim(x0,h, max(Re(polyroot(c(-y,1,0,-1))))  ,M))
StrangDataFix2$scheme <- "Fixed point"
StrangDataFix2$x0 <- x0
names(StrangDataFix2) <- c("sim","scheme", "Initial value")
StrangDataOpp2 <- data.frame(StrangSim(x0,h, min(Re(polyroot(c(-y,1,0,-1))))  ,M))
StrangDataOpp2$scheme <- "Opposite fixed point"
StrangDataOpp2$x0 <- x0
names(StrangDataOpp2) <- c("sim","scheme","Initial value")
StrangDataEachPoint2 <- data.frame(StrangSim(x0,h, x0  ,M))
StrangDataEachPoint2$scheme <- "Local Strang"
StrangDataEachPoint2$x0 <- x0
names(StrangDataEachPoint2) <- c("sim","scheme","Initial value")

data2 <- rbind(EMdata2,StrangDataFix2, StrangDataOpp2,StrangDataEachPoint2)
data <- rbind(data, data2)
names(data)<-c("sim","scheme","X_0")
data$scheme <- factor(data$scheme,levels=c('True distribution (EM)', 'Fixed point', 'Opposite fixed point','Local Strang'))


#Plot
appender <- function(string) 
    TeX(paste("$x_0 = $", string)) 

break_func <- function(x){if (mean(x)<0){
  c(x0_left,  -1, 0,1)
}else {
    c(-1, 0, x0, 1)
  }
}
label_func <- function(x){if (x[1]==-1.3){
  c(TeX('$x_0$'),  -1,0,1)
}else {
    c(-1, 0, TeX('$x_0$'), 1)
  }
}

p <- ggplot(data, aes(x=sim,color=scheme)) + geom_density(bw=0.15,lwd=1.5,key_glyph='path')+
  geom_vline(xintercept=median(Re(polyroot(c(-y,1,0,-1)))),col="darkgrey",linetype=2)+
  geom_vline(xintercept=min(Re(polyroot(c(-y,1,0,-1)))),col="darkgrey")+
  geom_vline(xintercept=max(Re(polyroot(c(-y,1,0,-1)))),col="darkgrey")+
  geom_vline(data=filter(data,X_0==x0_left),aes(xintercept=x0_left))+
  geom_vline(data=filter(data,X_0==x0),aes(xintercept=x0))+
  facet_wrap(~X_0,scales='free_x',labeller = as_labeller(appender, default = label_parsed) )+
  scale_color_manual(values=c("gold", "red", "blue","green4" )  )+
  guides(color=guide_legend(ncol=2))+
  scale_x_continuous(breaks=break_func,labels=label_func)+
  theme_bw(base_size=18 )+
  theme(axis.text.x=element_text(size=18) )+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())+
  theme(legend.position="bottom",#legend.key.size= unit(1.2, "cm"),
        legend.spacing.y=unit(0.02, "cm"),
        legend.box.spacing = unit(0.01, "cm"))+
  theme(strip.text.x = element_text(size = 16, color = "black", face = "bold"),
        strip.text.y = element_text(size = 16, color = "black", face = "bold"),
        strip.text = element_text(face="bold"),
        strip.background = element_rect(fill="grey")) +
  labs(x=TeX('$X_h$'),y="Density",color="Distribution")

p
```

